const { chromium, APP, OUT, handle } = require('./harness.cjs');
// The scout: patterns flagged on sample data, a dot on Insights, a Today line, Show on graph, Not interesting.
(async () => {
  const b = await chromium.launch(); const errs = [];
  const check = (label, ok) => { console.log((ok ? 'PASS ' : 'FAIL ') + label); if (!ok) process.exitCode = 1; };
  const ctx = await b.newContext({ viewport: { width: 1440, height: 1000 } });
  await ctx.route('https://ubfvaewfdbmecowoeuni.supabase.co/**', handle);
  const pg = await ctx.newPage();
  pg.on('pageerror', e => errs.push('pageerror: ' + e.message));
  pg.on('console', m => { if (m.type() === 'error' && !/ERR_CERT|fonts|Failed to load resource/.test(m.text())) errs.push('console: ' + m.text()); });
  await pg.goto(APP);
  await pg.fill('input[type=email]', 'lukacsarnold9+healthtest@gmail.com'); await pg.fill('input[type=password]', 'secret123');
  await pg.getByRole('button', { name: 'Sign in' }).click(); await pg.waitForSelector('text=Settings');
  check('new account: no dot, no line', await pg.locator('.tabdot').count() === 0);
  await pg.goto(APP + '#settings'); await pg.getByRole('button', { name: /Load sample/ }).click(); await pg.waitForTimeout(400);
  await pg.goto(APP + '#today'); await pg.waitForTimeout(500);
  const line = await pg.locator('.noticed-line').filter({ hasText: /Worth a look/i }).innerText().catch(() => '');
  check('Today shows a pattern you haven\'t seen', /\d+ of \d+ times/.test(line));
  check('Insights tab has a dot', await pg.locator('.tabdot').count() === 1);
  await pg.goto(APP + '#insights/connections'); await pg.waitForTimeout(800);
  const cards = pg.locator('.scard');
  const n = await cards.count();
  check('Insights lists patterns (sample data has some)', n >= 1);
  console.log((await pg.locator('#scout').innerText()).slice(0, 900));
  check('each says how often it held', /\d+ of \d+/.test(await cards.first().innerText()));
  await pg.locator('#scout').screenshot({ path: OUT + 'scout-cards.png' });
  await cards.first().getByRole('button', { name: 'Show on graph' }).click(); await pg.waitForTimeout(500);
  const checked = await pg.locator('.legend input[type=checkbox]:checked').count();
  check('Show on graph turns on just the two lanes', checked >= 1 && checked <= 2);
  await pg.locator('.master').screenshot({ path: OUT + 'scout-graph.png' });
  await pg.goto(APP + '#today'); await pg.waitForTimeout(300);
  check('seen on Insights → gone from Today and the dot', await pg.locator('.noticed-line').filter({ hasText: /Worth a look/i }).count() === 0 && await pg.locator('.tabdot').count() === 0);
  await pg.goto(APP + '#insights/connections'); await pg.waitForTimeout(500);
  const before = await pg.locator('.scard').count();
  await pg.locator('.scard').first().getByRole('button', { name: 'Not interesting' }).click(); await pg.waitForTimeout(300);
  check('Not interesting removes it', await pg.locator('.scard').count() === before - 1);
  console.log('errors:', JSON.stringify(errs));
  await b.close();
})().catch(e => { console.log('CRASH', e.message); process.exit(1); });
